### ISSUE TITLE
SPFx 1.14 support

### ISSUE THREAD

**Issue by msgx** [s-KaiNet/spfx-fast-serve-helpers#1]
When is it planned to release a package that supports SPFx v1.14? Currently, the following error appears:
> SPFx Fast Serve: version mismatch. We detected the usage of SPFx 1.14, but "spfx-fast-serve-helpers" version is 1.13.

**Comment by s-KaiNet** [comment]
If you've migrated, then you can just run `spfx-fast-serve` on top of the migrated project once again, and it should put the right version. Or just manually update the dependency as described [here](https://github.com/s-KaiNet/spfx-fast-serve#migration-between-spfx-versions). 
I totally forgot, that `spfx-fast-serve-helpers` for spfx 1.14 were still in beta, but I've just published the release version, so you shouldn't have any further problems.

**Comment by msgx** [comment]
> _...but I've just published the release version_

Thank you very much, Sergei. That's exactly what was needed.
